version: '3'
services:
  php:
    build: ./php
    image: php:latest
    container_name: php
    hostname: "php"
    volumes:
      - ./swagger-lumen:/var/www/html
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    working_dir: /var/www/html

  nginx:
    build: ./nginx
    image: nginx:latest
    container_name: nginx
    hostname: "nginx"
    ports:
      - "80:80"
    volumes:
      - ./swagger-lumen:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  swagger:
    image: swaggerapi/swagger-ui
    container_name: swagger
    environment:
      SWAGGER_JSON: /foo/swagger.json
    volumes:
      - ./swagger-lumen/public/swagger.json:/foo/swagger.json
    ports:
      - "8080:8080"
